export const INITIALIZE_POSTS = 'INITIALIZE_POSTS'
export const ADD_POST = 'ADD_POST'
export const EDIT_POST = 'EDIT_POST'
export const VOTE_POST = 'VOTE_POST'
export const DELETE_POST = 'DELETE_POST'

export const INITIALIZE_CATEGORIES = 'INITIALIZE_CATEGORIES'
export const CATEGORY_DATA = 'CATEGORY_DATA'

export const INITIALIZE_COMMENTS = 'INITIALIZE_COMMENTS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const VOTE_COMMENT = 'VOTE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const SORT_ASC = 'SORT_ASC';
export const SORT_DESC = 'SORT_DESC';
